### ISSUE TITLE
Github pages only showing content of readme.md

### ISSUE THREAD

**Issue by Nuub32User** [BharatKammakatla/Developer-Portfolio#1]
Sir, i forked this repo (your's) and then, added my github pages url in package.json

Now, when clicking on my github pages url - https://nuub32user.github.io/Developer-Portfolio/
It is only showing the conent stored in README.md instead of shwowing website content 🙁 
urgent help is needed.. help plz

**Comment by BharatKammakatla** [comment]
Hi Nuub,

Please follow the configuration steps in the same order as mentioned in README.md.
Also may I know have you followed the the steps as mentioned [here](https://create-react-app.dev/docs/deployment/#github-pages) while deploying ?
